### ISSUE TITLE
Can't test latest code

### ISSUE THREAD

**Issue by mbolo01** [tlk/beoplay-macos-remote-gui#21]
I have the following Xcode error:
<img width="273" alt="screenshot_108" src="https://user-images.githubusercontent.com/57586871/71363241-d2327400-2598-11ea-8c16-7da0fae65b8a.png">

Previous version works fine.
Kind regards,
Jérôme

**Comment by tlk** [comment]
Apologies, I was trimming the https://github.com/tlk/beoplay-macos-remote-cli/ repository with https://rtyley.github.io/bfg-repo-cleaner/ (to remove a large and unnecessary image file) and broke the contract that repository history never changes. I won't break the project like this again.

Upside it that the repository is now lighter, downside is that Xcode with a project already checked out will give the error you see. I also trimmed other dependencies so the project no longer depends on IBM-Kitura (and other IBM-*).


I believe this process should provide remediation. The key is to clean files that Xcode (rightfully) assumes will never change. Simply deleting the https://github.com/tlk/beoplay-macos-remote-gui project and checking it out again won't help because Xcode keeps the broken dependencies cached under the hood.

1. Temporarily remove https://github.com/tlk/beoplay-macos-remote-cli/ as a dependency:
     <img width="1080" alt="remove-dep" src="https://user-images.githubusercontent.com/90870/71365324-ea0cf680-259e-11ea-9f0c-cd0967eeedce.png">
2. Clean build: "Product", "Clean Build Folder"
3. Clean derived data folder: "File", "Project Settings", "Derived Data", click the tiny arrow and empty the folder:
    <img width="439" alt="derived-data" src="https://user-images.githubusercontent.com/90870/71365519-87682a80-259f-11ea-980c-2b459b3af4f5.png">
4. Add https://github.com/tlk/beoplay-macos-remote-cli/ back as a dependency
5. Build the project

Hope this helps!

**Comment by mbolo01** [comment]
Problem soled! Many thanks. TuneIn favorite fetch works very well, super improvement!

**Comment by tlk** [comment]
Happy to hear that!

**Comment by tlk** [comment]
It may be necessary to close Xcode before cleaning the derived data folder in step 3. While Xcode is closed you may need to delete `BeoplayRemoteGUI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`.

If the build issue persists after this, consider cleaning the derived data folder and deleting the beoplay-macos-remote-gui project to start over.
